import type {
  Product,
  ProductImage,
  ProductVariant,
  ProductFilters,
  PaginatedProducts,
  Category,
  Collection,
} from "@/types/product";
import type { Review, Address } from "@/types/user";
import type { Order } from "@/types/order";

// ─── Helpers ──────────────────────────────────────────────

const ts = "2024-06-01T00:00:00Z";

function makeImages(slug: string, count = 3): ProductImage[] {
  return Array.from({ length: count }, (_, i) => ({
    url: `/images/products/${slug}-${i + 1}.webp`,
    alt: `${slug} image ${i + 1}`,
  }));
}

function makeVariants(
  colors: string[],
  sizes: string[],
  basePrice: number,
  baseStock = 12
): ProductVariant[] {
  const variants: ProductVariant[] = [];
  for (const color of colors) {
    for (const size of sizes) {
      variants.push({
        variantId: `${color.toLowerCase()}-${size.toLowerCase()}`,
        size,
        color,
        stock: Math.max(0, baseStock + Math.floor(Math.random() * 8) - 4),
        price: basePrice,
      });
    }
  }
  return variants;
}

// ─── Categories ───────────────────────────────────────────

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Corsets",
    slug: "corsets",
    description: "Sculpted silhouettes that empower. Handcrafted corsets with boning, busk closures, and luxurious fabrics.",
    imageUrl: null,
    parentId: null,
    showInMenu: true,
    displayOrder: 1,
    metaTitle: "Luxury Corsets | Maison ISIVIS",
    metaDescription: "Handcrafted luxury corsets from our London atelier. Sculpted silhouettes for the modern woman.",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "cat-2",
    name: "Dresses",
    slug: "dresses",
    description: "Elegance in every stitch. From midi to maxi, discover handcrafted dresses that turn heads.",
    imageUrl: null,
    parentId: null,
    showInMenu: true,
    displayOrder: 2,
    metaTitle: "Luxury Dresses | Maison ISIVIS",
    metaDescription: "Handcrafted luxury dresses from our London atelier.",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "cat-3",
    name: "Tops",
    slug: "tops",
    description: "Statement pieces crafted from the finest fabrics. Blouses, bodysuits, and beyond.",
    imageUrl: null,
    parentId: null,
    showInMenu: true,
    displayOrder: 3,
    metaTitle: "Luxury Tops | Maison ISIVIS",
    metaDescription: "Premium tops and blouses handcrafted in London.",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "cat-4",
    name: "Bottoms",
    slug: "bottoms",
    description: "Tailored trousers, flowing skirts, and everything in between.",
    imageUrl: null,
    parentId: null,
    showInMenu: true,
    displayOrder: 4,
    metaTitle: "Luxury Bottoms | Maison ISIVIS",
    metaDescription: "Premium skirts and trousers from Maison ISIVIS.",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "cat-5",
    name: "Jumpsuits",
    slug: "jumpsuits",
    description: "One-piece wonders. Effortlessly chic jumpsuits and playsuits for every occasion.",
    imageUrl: null,
    parentId: null,
    showInMenu: true,
    displayOrder: 5,
    metaTitle: "Luxury Jumpsuits | Maison ISIVIS",
    metaDescription: "Designer jumpsuits handcrafted in our London atelier.",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "cat-6",
    name: "Co-ords",
    slug: "co-ords",
    description: "Matching sets to slay. Perfectly paired luxury co-ord sets.",
    imageUrl: null,
    parentId: null,
    showInMenu: true,
    displayOrder: 6,
    metaTitle: "Luxury Co-ords | Maison ISIVIS",
    metaDescription: "Luxury matching sets from Maison ISIVIS.",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "cat-7",
    name: "Outerwear",
    slug: "outerwear",
    description: "Capes, blazers, and coats that command attention.",
    imageUrl: null,
    parentId: null,
    showInMenu: true,
    displayOrder: 7,
    metaTitle: "Luxury Outerwear | Maison ISIVIS",
    metaDescription: "Premium outerwear handcrafted in our London atelier.",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "cat-8",
    name: "Lounge and Intimates",
    slug: "lounge-and-intimates",
    description: "Luxurious loungewear and intimates for your most indulgent moments.",
    imageUrl: null,
    parentId: null,
    showInMenu: true,
    displayOrder: 8,
    metaTitle: "Luxury Loungewear & Intimates | Maison ISIVIS",
    metaDescription: "Premium loungewear and intimates from Maison ISIVIS.",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "cat-9",
    name: "Swimwear",
    slug: "swimwear",
    description: "Resort-ready luxury. Swimsuits and cover-ups for the discerning woman.",
    imageUrl: null,
    parentId: null,
    showInMenu: true,
    displayOrder: 9,
    metaTitle: "Luxury Swimwear | Maison ISIVIS",
    metaDescription: "Designer swimwear from Maison ISIVIS.",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "cat-10",
    name: "Active Wear",
    slug: "active-wear",
    description: "Performance meets luxury. Activewear that moves with you in style.",
    imageUrl: null,
    parentId: null,
    showInMenu: true,
    displayOrder: 10,
    metaTitle: "Luxury Active Wear | Maison ISIVIS",
    metaDescription: "Premium activewear from Maison ISIVIS.",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "cat-11",
    name: "Accessories",
    slug: "accessories",
    description: "The finishing touches. Belts, scarves, and statement pieces.",
    imageUrl: null,
    parentId: null,
    showInMenu: true,
    displayOrder: 11,
    metaTitle: "Luxury Accessories | Maison ISIVIS",
    metaDescription: "Luxury accessories from Maison ISIVIS.",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "cat-12",
    name: "Gift Cards",
    slug: "gift-cards",
    description: "The perfect gift. Let them choose their own luxury from Maison ISIVIS.",
    imageUrl: null,
    parentId: null,
    showInMenu: true,
    displayOrder: 12,
    metaTitle: "Gift Cards | Maison ISIVIS",
    metaDescription: "Maison ISIVIS gift cards. The perfect luxury gift.",
    createdAt: ts,
    updatedAt: ts,
  },
];

// ─── Collections ──────────────────────────────────────────

export const MOCK_COLLECTIONS: Collection[] = [
  {
    id: "col-1",
    title: "Best Sellers",
    slug: "best-sellers",
    description: "Our most loved pieces, chosen by women who know what they want.",
    heroImageUrl: null,
    heroVideoUrl: null,
    collectionType: "featured",
    featured: true,
    displayOrder: 1,
    metaTitle: "Best Sellers | Maison ISIVIS",
    metaDescription: "Shop our most popular luxury pieces.",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "col-2",
    title: "Old Money",
    slug: "old-money",
    description: "Timeless elegance reimagined. Classic silhouettes with modern luxury.",
    heroImageUrl: "/images/collections/Old Money.webp",
    heroVideoUrl: null,
    collectionType: "style",
    featured: true,
    displayOrder: 2,
    metaTitle: "Old Money Collection | Maison ISIVIS",
    metaDescription: "Timeless elegance reimagined for the modern woman.",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "col-3",
    title: "Fierce",
    slug: "fierce",
    description: "Bold statements for fearless women. Crystal embellishments and show-stopping silhouettes.",
    heroImageUrl: null,
    heroVideoUrl: null,
    collectionType: "style",
    featured: true,
    displayOrder: 3,
    metaTitle: "Fierce Collection | Maison ISIVIS",
    metaDescription: "Bold luxury fashion for fearless women.",
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "col-4",
    title: "Contemporary",
    slug: "contemporary",
    description: "Modern luxury meets classic sophistication. Flowing silks and romantic drapery.",
    heroImageUrl: null,
    heroVideoUrl: null,
    collectionType: "style",
    featured: true,
    displayOrder: 4,
    metaTitle: "Contemporary Collection | Maison ISIVIS",
    metaDescription: "Modern luxury fashion from Maison ISIVIS.",
    createdAt: ts,
    updatedAt: ts,
  },
];

// ─── Products ─────────────────────────────────────────────

export const MOCK_PRODUCTS: Product[] = [
  // ── Dresses (cat-1) ──
  {
    id: "prod-1",
    name: "Selene Silk Midi Dress",
    slug: "selene-silk-midi-dress",
    sku: "ISV-DR-001",
    shortDescription: "A flowing silk midi with romantic draping and a fitted bodice.",
    description: "The Selene is our signature silk midi dress, featuring a sculpted bodice with romantic draping that cascades into a fluid skirt. Handcrafted from 100% mulberry silk in our London atelier, this piece embodies timeless femininity. The concealed side zip ensures a seamless silhouette, while the adjustable straps allow a customised fit. Pair with our signature heels for an unforgettable evening look.",
    price: 298,
    salePrice: null,
    compareAtPrice: null,
    inStock: true,
    stockQuantity: 24,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("selene-silk-midi-dress"),
    videoUrl: null,
    categoryId: "cat-2",
    categoryIds: ["cat-2"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Ivory", "Black"], ["XS", "S", "M", "L", "XL"], 298),
    fabric: "100% Mulberry Silk",
    careInstructions: "Dry clean only. Store on padded hanger. Steam to remove creases.",
    measurements: { "Bust (S)": "86cm", "Waist (S)": "68cm", "Length (S)": "115cm" },
    featured: true,
    newArrival: false,
    bestseller: true,
    badge: "Best Seller",
    metaTitle: "Selene Silk Midi Dress | Maison ISIVIS",
    metaDescription: "Flowing silk midi dress handcrafted in our London atelier.",
    keywords: ["silk dress", "midi dress", "luxury dress"],
    displayOrder: 1,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "prod-2",
    name: "Aurora Crystal Gown",
    slug: "aurora-crystal-gown",
    sku: "ISV-DR-002",
    shortDescription: "A floor-length gown adorned with hand-sewn crystal embellishments.",
    description: "The Aurora is a statement piece for the woman who demands to be noticed. This floor-length gown features thousands of hand-sewn Swarovski crystals cascading across a fitted bodice, flowing into a dramatic tulle skirt. Each crystal is individually placed by our master artisans, making every dress unique. A corset-style back ensures a perfect fit.",
    price: 648,
    salePrice: 548,
    compareAtPrice: 648,
    inStock: true,
    stockQuantity: 8,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("aurora-crystal-gown", 4),
    videoUrl: null,
    categoryId: "cat-2",
    categoryIds: ["cat-2"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Diamond", "Black"], ["XS", "S", "M", "L"], 648),
    fabric: "Tulle overlay, Silk lining, Swarovski crystals",
    careInstructions: "Professional clean only. Store in garment bag. Handle crystals with care.",
    measurements: { "Bust (S)": "84cm", "Waist (S)": "66cm", "Length (S)": "155cm" },
    featured: true,
    newArrival: false,
    bestseller: true,
    badge: "Best Seller",
    metaTitle: "Aurora Crystal Gown | Maison ISIVIS",
    metaDescription: "Hand-embellished crystal gown from Maison ISIVIS.",
    keywords: ["crystal gown", "evening gown", "luxury gown"],
    displayOrder: 2,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "prod-3",
    name: "Celeste Lace Corset Dress",
    slug: "celeste-lace-corset-dress",
    sku: "ISV-DR-003",
    shortDescription: "Romantic lace corset dress with a sweetheart neckline and full skirt.",
    description: "The Celeste combines the structure of a hand-boned corset with the romance of French lace. The sweetheart neckline frames the décolletage beautifully, while the full skirt creates a timeless silhouette. Crafted from premium French Chantilly lace over a silk lining, with hand-finished boning for structure and support.",
    price: 398,
    salePrice: null,
    compareAtPrice: null,
    inStock: true,
    stockQuantity: 15,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("celeste-lace-corset-dress"),
    videoUrl: null,
    categoryId: "cat-2",
    categoryIds: ["cat-2"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Ivory", "Red"], ["XS", "S", "M", "L", "XL"], 398),
    fabric: "French Chantilly Lace, Silk lining, Steel boning",
    careInstructions: "Dry clean only. Store flat or on padded hanger.",
    measurements: { "Bust (S)": "82cm", "Waist (S)": "64cm", "Length (S)": "120cm" },
    featured: false,
    newArrival: true,
    bestseller: false,
    badge: "New",
    metaTitle: "Celeste Lace Corset Dress | Maison ISIVIS",
    metaDescription: "Romantic lace corset dress from our London atelier.",
    keywords: ["lace dress", "corset dress", "luxury dress"],
    displayOrder: 3,
    published: true,
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: "2025-01-15T00:00:00Z",
  },
  {
    id: "prod-4",
    name: "Valentina Velvet Wrap Dress",
    slug: "valentina-velvet-wrap-dress",
    sku: "ISV-DR-004",
    shortDescription: "Sumptuous velvet wrap dress with a dramatic neckline.",
    description: "The Valentina is luxury at its most tactile. Crafted from premium Italian silk velvet, this wrap dress hugs the body in all the right places. The deep V-neckline adds drama, while the self-tie waist creates a flattering silhouette. Perfect for intimate dinners and special occasions.",
    price: 268,
    salePrice: 198,
    compareAtPrice: 268,
    inStock: true,
    stockQuantity: 20,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("valentina-velvet-wrap-dress"),
    videoUrl: null,
    categoryId: "cat-2",
    categoryIds: ["cat-2"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Black", "Red"], ["XS", "S", "M", "L", "XL", "XXL"], 268),
    fabric: "Italian Silk Velvet",
    careInstructions: "Dry clean recommended. Steam velvet gently to restore pile.",
    measurements: { "Bust (S)": "88cm", "Waist (S)": "70cm", "Length (S)": "110cm" },
    featured: false,
    newArrival: false,
    bestseller: false,
    badge: "Sale",
    metaTitle: "Valentina Velvet Wrap Dress | Maison ISIVIS",
    metaDescription: "Italian silk velvet wrap dress from Maison ISIVIS.",
    keywords: ["velvet dress", "wrap dress", "luxury dress"],
    displayOrder: 4,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── Tops (cat-2) ──
  {
    id: "prod-5",
    name: "Aria Crystal Corset",
    slug: "aria-crystal-corset",
    sku: "ISV-TP-001",
    shortDescription: "Hand-beaded crystal corset with structured boning.",
    description: "The Aria is the corset reimagined for the modern woman. Featuring hundreds of hand-sewn crystals over premium duchess satin, with steel boning for perfect structure. A lace-up back allows customised fit. Style with high-waisted trousers for a night out or layer under a blazer for unexpected sophistication.",
    price: 248,
    salePrice: null,
    compareAtPrice: null,
    inStock: true,
    stockQuantity: 18,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("aria-crystal-corset"),
    videoUrl: null,
    categoryId: "cat-3",
    categoryIds: ["cat-3"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Diamond", "Black", "Ivory"], ["XS", "S", "M", "L"], 248),
    fabric: "Duchess Satin, Steel boning, Crystal embellishments",
    careInstructions: "Spot clean only. Store flat. Handle crystals carefully.",
    measurements: { "Bust (S)": "82cm", "Waist (S)": "64cm", "Length (S)": "35cm" },
    featured: true,
    newArrival: false,
    bestseller: true,
    badge: "Best Seller",
    metaTitle: "Aria Crystal Corset | Maison ISIVIS",
    metaDescription: "Hand-beaded crystal corset from Maison ISIVIS.",
    keywords: ["crystal corset", "corset top", "luxury top"],
    displayOrder: 1,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "prod-6",
    name: "Luna Silk Camisole",
    slug: "luna-silk-camisole",
    sku: "ISV-TP-002",
    shortDescription: "Delicate silk camisole with French lace trim.",
    description: "The Luna camisole is effortless luxury. Cut from the finest mulberry silk with delicate French lace trim at the neckline and hem. The bias cut drapes beautifully, creating an elegant silhouette. Pair with our tailored trousers or wear as a luxurious layering piece.",
    price: 128,
    salePrice: null,
    compareAtPrice: null,
    inStock: true,
    stockQuantity: 30,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("luna-silk-camisole"),
    videoUrl: null,
    categoryId: "cat-3",
    categoryIds: ["cat-3"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Ivory", "Black", "Beige"], ["XS", "S", "M", "L", "XL"], 128),
    fabric: "100% Mulberry Silk, French lace trim",
    careInstructions: "Hand wash cold. Lay flat to dry. Low iron on reverse.",
    measurements: { "Bust (S)": "84cm", "Length (S)": "55cm" },
    featured: false,
    newArrival: true,
    bestseller: false,
    badge: "New",
    metaTitle: "Luna Silk Camisole | Maison ISIVIS",
    metaDescription: "Mulberry silk camisole with French lace trim.",
    keywords: ["silk camisole", "lace top", "luxury top"],
    displayOrder: 2,
    published: true,
    createdAt: "2025-02-01T00:00:00Z",
    updatedAt: "2025-02-01T00:00:00Z",
  },
  {
    id: "prod-7",
    name: "Mia Pearl Blouse",
    slug: "mia-pearl-blouse",
    sku: "ISV-TP-003",
    shortDescription: "Organza blouse with hand-sewn pearl embellishments.",
    description: "The Mia blouse elevates any ensemble. Crafted from Italian organza with hundreds of freshwater pearls hand-sewn across the bodice. Balloon sleeves add drama while the fitted waist keeps the silhouette elegant. A statement piece that pairs beautifully with tailored trousers or a pencil skirt.",
    price: 189,
    salePrice: null,
    compareAtPrice: null,
    inStock: true,
    stockQuantity: 12,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("mia-pearl-blouse"),
    videoUrl: null,
    categoryId: "cat-3",
    categoryIds: ["cat-3"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["White", "Ivory"], ["XS", "S", "M", "L"], 189),
    fabric: "Italian Organza, Freshwater pearls",
    careInstructions: "Dry clean only. Store on padded hanger.",
    measurements: { "Bust (S)": "90cm", "Waist (S)": "72cm", "Length (S)": "60cm" },
    featured: false,
    newArrival: false,
    bestseller: false,
    badge: null,
    metaTitle: "Mia Pearl Blouse | Maison ISIVIS",
    metaDescription: "Pearl-embellished organza blouse from Maison ISIVIS.",
    keywords: ["pearl blouse", "organza top", "luxury blouse"],
    displayOrder: 3,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "prod-8",
    name: "Ivy Draped Bodysuit",
    slug: "ivy-draped-bodysuit",
    sku: "ISV-TP-004",
    shortDescription: "Sculpted bodysuit with asymmetric draping in jersey.",
    description: "The Ivy bodysuit is a modern essential. Sculpted from premium Italian jersey with asymmetric draping that flatters every figure. The snap closure ensures comfort, while the strategic gathering accentuates curves. Versatile enough for day-to-night dressing.",
    price: 120,
    salePrice: 89,
    compareAtPrice: 120,
    inStock: true,
    stockQuantity: 22,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("ivy-draped-bodysuit"),
    videoUrl: null,
    categoryId: "cat-3",
    categoryIds: ["cat-3"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Black", "White", "Beige"], ["XS", "S", "M", "L", "XL"], 120),
    fabric: "Premium Italian Jersey",
    careInstructions: "Machine wash cold gentle. Lay flat to dry.",
    measurements: { "Bust (S)": "84cm", "Waist (S)": "66cm" },
    featured: false,
    newArrival: false,
    bestseller: false,
    badge: "Sale",
    metaTitle: "Ivy Draped Bodysuit | Maison ISIVIS",
    metaDescription: "Italian jersey draped bodysuit from Maison ISIVIS.",
    keywords: ["bodysuit", "draped top", "luxury bodysuit"],
    displayOrder: 4,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── Bottoms (cat-3) ──
  {
    id: "prod-9",
    name: "Serena Tailored Trousers",
    slug: "serena-tailored-trousers",
    sku: "ISV-BT-001",
    shortDescription: "High-waisted tailored trousers in wool-blend crepe.",
    description: "The Serena trousers are the foundation of an impeccable wardrobe. Cut from Italian wool-blend crepe with a high waist and wide leg, they create a long, lean silhouette. The invisible side zip and pressed centre crease ensure a polished finish. An everyday luxury piece.",
    price: 198,
    salePrice: null,
    compareAtPrice: null,
    inStock: true,
    stockQuantity: 25,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("serena-tailored-trousers"),
    videoUrl: null,
    categoryId: "cat-4",
    categoryIds: ["cat-4"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Black", "Ivory", "Beige"], ["XS", "S", "M", "L", "XL", "XXL"], 198),
    fabric: "Italian Wool-blend Crepe",
    careInstructions: "Dry clean recommended. Press on medium heat.",
    measurements: { "Waist (S)": "66cm", "Hip (S)": "92cm", "Inseam (S)": "80cm" },
    featured: true,
    newArrival: false,
    bestseller: true,
    badge: "Best Seller",
    metaTitle: "Serena Tailored Trousers | Maison ISIVIS",
    metaDescription: "Italian wool-blend tailored trousers from Maison ISIVIS.",
    keywords: ["tailored trousers", "wide leg trousers", "luxury trousers"],
    displayOrder: 1,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "prod-10",
    name: "Elara Silk Midi Skirt",
    slug: "elara-silk-midi-skirt",
    sku: "ISV-BT-002",
    shortDescription: "Flowing silk midi skirt with bias cut.",
    description: "The Elara skirt is pure romance. Cut on the bias from luxurious charmeuse silk, it moves like liquid. The elasticated waistband provides comfort without compromising on elegance. Perfect for both daytime sophistication and evening glamour.",
    price: 168,
    salePrice: null,
    compareAtPrice: null,
    inStock: true,
    stockQuantity: 16,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("elara-silk-midi-skirt"),
    videoUrl: null,
    categoryId: "cat-4",
    categoryIds: ["cat-4"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Ivory", "Black", "Beige"], ["XS", "S", "M", "L"], 168),
    fabric: "100% Charmeuse Silk",
    careInstructions: "Dry clean only. Steam to remove wrinkles.",
    measurements: { "Waist (S)": "66cm", "Length (S)": "78cm" },
    featured: false,
    newArrival: true,
    bestseller: false,
    badge: "New",
    metaTitle: "Elara Silk Midi Skirt | Maison ISIVIS",
    metaDescription: "Bias-cut silk midi skirt from Maison ISIVIS.",
    keywords: ["silk skirt", "midi skirt", "luxury skirt"],
    displayOrder: 2,
    published: true,
    createdAt: "2025-01-20T00:00:00Z",
    updatedAt: "2025-01-20T00:00:00Z",
  },
  {
    id: "prod-11",
    name: "Victoria Pleated Palazzo",
    slug: "victoria-pleated-palazzo",
    sku: "ISV-BT-003",
    shortDescription: "Permanently pleated wide-leg palazzo trousers.",
    description: "The Victoria palazzo trousers bring effortless drama. Permanently pleated from premium polyester-blend fabric, they create beautiful movement with every step. The high waist and pull-on elasticated waistband combine style with ease. Dress up with a corset or keep it casual with a camisole.",
    price: 158,
    salePrice: 126,
    compareAtPrice: 158,
    inStock: true,
    stockQuantity: 18,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("victoria-pleated-palazzo"),
    videoUrl: null,
    categoryId: "cat-4",
    categoryIds: ["cat-4"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Black", "Beige", "White"], ["S", "M", "L", "XL"], 158),
    fabric: "Premium Polyester-blend, Permanent pleat finish",
    careInstructions: "Machine wash cold. Hang to dry. Do not iron on pleats.",
    measurements: { "Waist (S)": "66cm", "Inseam (S)": "82cm" },
    featured: false,
    newArrival: false,
    bestseller: false,
    badge: "Sale",
    metaTitle: "Victoria Pleated Palazzo | Maison ISIVIS",
    metaDescription: "Pleated palazzo trousers from Maison ISIVIS.",
    keywords: ["palazzo trousers", "pleated trousers", "wide leg"],
    displayOrder: 3,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "prod-12",
    name: "Dahlia Pencil Skirt",
    slug: "dahlia-pencil-skirt",
    sku: "ISV-BT-004",
    shortDescription: "Classic pencil skirt in Italian stretch wool.",
    description: "The Dahlia is the ultimate power dressing essential. Cut from Italian stretch wool with a high waist and back vent, it creates a sharp, feminine silhouette. The fully lined interior ensures all-day comfort. Pair with any of our blouses for a commanding presence.",
    price: 148,
    salePrice: null,
    compareAtPrice: null,
    inStock: true,
    stockQuantity: 20,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("dahlia-pencil-skirt"),
    videoUrl: null,
    categoryId: "cat-4",
    categoryIds: ["cat-4"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Black", "Red"], ["XS", "S", "M", "L", "XL"], 148),
    fabric: "Italian Stretch Wool",
    careInstructions: "Dry clean only.",
    measurements: { "Waist (S)": "66cm", "Hip (S)": "92cm", "Length (S)": "62cm" },
    featured: false,
    newArrival: false,
    bestseller: false,
    badge: null,
    metaTitle: "Dahlia Pencil Skirt | Maison ISIVIS",
    metaDescription: "Italian wool pencil skirt from Maison ISIVIS.",
    keywords: ["pencil skirt", "wool skirt", "luxury skirt"],
    displayOrder: 4,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── Co-ords (cat-4) ──
  {
    id: "prod-13",
    name: "Celestial Silk Co-ord",
    slug: "celestial-silk-co-ord",
    sku: "ISV-CO-001",
    shortDescription: "Matching silk crop top and palazzo set with crystal details.",
    description: "The Celestial co-ord is a showstopper. A cropped silk top with crystal straps paired with flowing palazzo trousers. Both pieces work beautifully together or as separates. Handcrafted from premium silk with hand-sewn crystal details that catch the light with every movement.",
    price: 448,
    salePrice: null,
    compareAtPrice: null,
    inStock: true,
    stockQuantity: 10,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("celestial-silk-co-ord", 4),
    videoUrl: null,
    categoryId: "cat-6",
    categoryIds: ["cat-6"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Ivory", "Black"], ["XS", "S", "M", "L"], 448),
    fabric: "100% Silk, Crystal embellishments",
    careInstructions: "Dry clean only. Store separately. Handle crystals with care.",
    measurements: { "Top Bust (S)": "82cm", "Trouser Waist (S)": "66cm", "Trouser Inseam (S)": "80cm" },
    featured: true,
    newArrival: false,
    bestseller: true,
    badge: "Best Seller",
    metaTitle: "Celestial Silk Co-ord | Maison ISIVIS",
    metaDescription: "Silk co-ord set with crystal details from Maison ISIVIS.",
    keywords: ["co-ord set", "silk set", "matching set"],
    displayOrder: 1,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "prod-14",
    name: "Irena Tweed Co-ord",
    slug: "irena-tweed-co-ord",
    sku: "ISV-CO-002",
    shortDescription: "Classic tweed jacket and skirt set with gold button details.",
    description: "The Irena channels Parisian chic with a London twist. A structured tweed jacket with gold buttons paired with a matching high-waisted mini skirt. The jacket features patch pockets and frayed edges for texture, while the skirt has a comfortable A-line silhouette. Old money elegance at its finest.",
    price: 398,
    salePrice: 328,
    compareAtPrice: 398,
    inStock: true,
    stockQuantity: 14,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("irena-tweed-co-ord", 4),
    videoUrl: null,
    categoryId: "cat-6",
    categoryIds: ["cat-6"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Ivory", "Beige"], ["XS", "S", "M", "L", "XL"], 398),
    fabric: "Italian Bouclé Tweed, Silk lining",
    careInstructions: "Dry clean only. Store on padded hanger.",
    measurements: { "Jacket Bust (S)": "88cm", "Skirt Waist (S)": "66cm", "Skirt Length (S)": "45cm" },
    featured: false,
    newArrival: false,
    bestseller: false,
    badge: "Sale",
    metaTitle: "Irena Tweed Co-ord | Maison ISIVIS",
    metaDescription: "Classic tweed co-ord set from Maison ISIVIS.",
    keywords: ["tweed set", "co-ord", "matching set", "old money"],
    displayOrder: 2,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "prod-15",
    name: "Nova Knit Loungewear Set",
    slug: "nova-knit-loungewear-set",
    sku: "ISV-CO-003",
    shortDescription: "Cashmere-blend knit top and trouser set for luxurious lounging.",
    description: "The Nova set redefines loungewear. Crafted from a sumptuous cashmere-wool blend, the relaxed crop top and wide-leg trousers offer unparalleled softness. The ribbed details add texture while maintaining a clean, minimal aesthetic. Luxurious comfort for at home or on the go.",
    price: 348,
    salePrice: null,
    compareAtPrice: null,
    inStock: true,
    stockQuantity: 3,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("nova-knit-loungewear-set"),
    videoUrl: null,
    categoryId: "cat-6",
    categoryIds: ["cat-6"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Beige", "Ivory"], ["S", "M", "L"], 348),
    fabric: "70% Cashmere, 30% Wool",
    careInstructions: "Hand wash cold with cashmere shampoo. Lay flat to dry. Do not wring.",
    measurements: { "Top Bust (S)": "90cm", "Trouser Waist (S)": "68cm" },
    featured: false,
    newArrival: true,
    bestseller: false,
    badge: "New",
    metaTitle: "Nova Knit Loungewear Set | Maison ISIVIS",
    metaDescription: "Cashmere-blend loungewear set from Maison ISIVIS.",
    keywords: ["cashmere set", "loungewear", "knit co-ord"],
    displayOrder: 3,
    published: true,
    createdAt: "2025-02-10T00:00:00Z",
    updatedAt: "2025-02-10T00:00:00Z",
  },
  {
    id: "prod-16",
    name: "Rosalie Satin Co-ord",
    slug: "rosalie-satin-co-ord",
    sku: "ISV-CO-004",
    shortDescription: "Draped satin wrap top with matching wide-leg trousers.",
    description: "The Rosalie set is evening sophistication made simple. A draped wrap top in lustrous satin paired with high-waisted wide-leg trousers. The top features a self-tie closure for adjustable fit, while the trousers have a concealed side zip. Wear together or style as versatile separates.",
    price: 328,
    salePrice: null,
    compareAtPrice: null,
    inStock: true,
    stockQuantity: 16,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("rosalie-satin-co-ord"),
    videoUrl: null,
    categoryId: "cat-6",
    categoryIds: ["cat-6"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Black", "Ivory", "Red"], ["XS", "S", "M", "L"], 328),
    fabric: "Premium Duchess Satin",
    careInstructions: "Dry clean only. Steam on low heat.",
    measurements: { "Top Bust (S)": "86cm", "Trouser Waist (S)": "66cm", "Trouser Inseam (S)": "80cm" },
    featured: false,
    newArrival: false,
    bestseller: false,
    badge: null,
    metaTitle: "Rosalie Satin Co-ord | Maison ISIVIS",
    metaDescription: "Satin co-ord set from Maison ISIVIS.",
    keywords: ["satin set", "co-ord", "evening set"],
    displayOrder: 4,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── Outerwear (cat-5) ──
  {
    id: "prod-17",
    name: "Empress Vegan Fur Cape",
    slug: "empress-vegan-fur-cape",
    sku: "ISV-OW-001",
    shortDescription: "Luxurious vegan fur cape with silk lining.",
    description: "The Empress cape is drama personified. Crafted from the most luxurious vegan fur with a silk lining, it drapes over the shoulders to create a regal silhouette. The hidden hook closure keeps it secure, while the generous cut allows it to be styled over dresses and evening wear. A statement of conscious luxury.",
    price: 498,
    salePrice: null,
    compareAtPrice: null,
    inStock: true,
    stockQuantity: 6,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("empress-vegan-fur-cape"),
    videoUrl: null,
    categoryId: "cat-7",
    categoryIds: ["cat-7"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Ivory", "Black"], ["S/M", "L/XL"], 498),
    fabric: "Premium Vegan Fur, Silk lining",
    careInstructions: "Professional fur clean only. Store in cool, dry place.",
    measurements: { "Length (S/M)": "85cm", "Width (S/M)": "140cm" },
    featured: true,
    newArrival: false,
    bestseller: false,
    badge: "Limited Edition",
    metaTitle: "Empress Vegan Fur Cape | Maison ISIVIS",
    metaDescription: "Luxurious vegan fur cape from Maison ISIVIS.",
    keywords: ["vegan fur", "cape", "luxury outerwear"],
    displayOrder: 1,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "prod-18",
    name: "Athena Structured Blazer",
    slug: "athena-structured-blazer",
    sku: "ISV-OW-002",
    shortDescription: "Double-breasted blazer in Italian wool with gold buttons.",
    description: "The Athena blazer is power dressing at its finest. Double-breasted with signature gold buttons, cut from Italian virgin wool with a nipped waist and structured shoulders. The fully silk-lined interior ensures comfort and a smooth drape. A timeless investment piece for the modern woman.",
    price: 348,
    salePrice: null,
    compareAtPrice: null,
    inStock: true,
    stockQuantity: 14,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("athena-structured-blazer"),
    videoUrl: null,
    categoryId: "cat-7",
    categoryIds: ["cat-7"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Black", "Ivory", "Beige"], ["XS", "S", "M", "L", "XL"], 348),
    fabric: "Italian Virgin Wool, Silk lining",
    careInstructions: "Dry clean only. Store on wide hanger to maintain shape.",
    measurements: { "Bust (S)": "90cm", "Waist (S)": "74cm", "Length (S)": "68cm" },
    featured: false,
    newArrival: false,
    bestseller: true,
    badge: "Best Seller",
    metaTitle: "Athena Structured Blazer | Maison ISIVIS",
    metaDescription: "Italian wool double-breasted blazer from Maison ISIVIS.",
    keywords: ["wool blazer", "structured blazer", "luxury blazer"],
    displayOrder: 2,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "prod-19",
    name: "Ophelia Organza Duster",
    slug: "ophelia-organza-duster",
    sku: "ISV-OW-003",
    shortDescription: "Sheer organza duster coat with dramatic floor-length silhouette.",
    description: "The Ophelia duster is ethereal layering at its most dramatic. Floor-length sheer organza with delicate floral embroidery creates a dreamlike overlay for any outfit. The open-front design and dramatic sleeves add movement and romance. Perfect for outdoor events and garden parties.",
    price: 278,
    salePrice: null,
    compareAtPrice: null,
    inStock: true,
    stockQuantity: 9,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("ophelia-organza-duster"),
    videoUrl: null,
    categoryId: "cat-7",
    categoryIds: ["cat-7"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["White", "Ivory"], ["S", "M", "L"], 278),
    fabric: "Italian Organza, Embroidery thread",
    careInstructions: "Dry clean only. Store on padded hanger.",
    measurements: { "Bust (S)": "100cm", "Length (S)": "145cm" },
    featured: false,
    newArrival: true,
    bestseller: false,
    badge: "New",
    metaTitle: "Ophelia Organza Duster | Maison ISIVIS",
    metaDescription: "Embroidered organza duster from Maison ISIVIS.",
    keywords: ["organza coat", "duster", "sheer coat"],
    displayOrder: 3,
    published: true,
    createdAt: "2025-01-25T00:00:00Z",
    updatedAt: "2025-01-25T00:00:00Z",
  },
  {
    id: "prod-20",
    name: "Raven Leather Jacket",
    slug: "raven-leather-jacket",
    sku: "ISV-OW-004",
    shortDescription: "Cropped biker jacket in butter-soft Italian leather.",
    description: "The Raven jacket adds edge to elegance. Cropped and fitted in butter-soft Italian lambskin leather with silver hardware. The asymmetric zip closure, snap collar, and zip pockets give it classic biker attitude, while the tailored fit keeps it unmistakably ISIVIS. Layer over a dress for unexpected contrast.",
    price: 548,
    salePrice: 448,
    compareAtPrice: 548,
    inStock: true,
    stockQuantity: 7,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("raven-leather-jacket"),
    videoUrl: null,
    categoryId: "cat-7",
    categoryIds: ["cat-7"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Black"], ["XS", "S", "M", "L", "XL"], 548),
    fabric: "Italian Lambskin Leather, Cotton lining",
    careInstructions: "Professional leather clean only. Condition regularly.",
    measurements: { "Bust (S)": "88cm", "Length (S)": "48cm" },
    featured: false,
    newArrival: false,
    bestseller: false,
    badge: "Sale",
    metaTitle: "Raven Leather Jacket | Maison ISIVIS",
    metaDescription: "Italian lambskin leather jacket from Maison ISIVIS.",
    keywords: ["leather jacket", "biker jacket", "luxury jacket"],
    displayOrder: 4,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },

  // ── Accessories (cat-6) ──
  {
    id: "prod-21",
    name: "Solstice Crystal Belt",
    slug: "solstice-crystal-belt",
    sku: "ISV-AC-001",
    shortDescription: "Hand-embellished crystal waist belt in satin.",
    description: "The Solstice belt transforms any outfit. Hand-embellished with hundreds of crystals on a satin base, it cinches the waist to create a stunning focal point. The hook closure at the back is adjustable for a perfect fit. Wear over dresses, blazers, or knitwear for instant glamour.",
    price: 128,
    salePrice: null,
    compareAtPrice: null,
    inStock: true,
    stockQuantity: 20,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("solstice-crystal-belt"),
    videoUrl: null,
    categoryId: "cat-11",
    categoryIds: ["cat-11"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Diamond", "Black"], ["S", "M", "L"], 128),
    fabric: "Satin, Crystal embellishments, Metal hardware",
    careInstructions: "Store flat. Handle crystals carefully. Spot clean only.",
    measurements: { "Width": "6cm", "Length (S)": "70cm" },
    featured: false,
    newArrival: false,
    bestseller: false,
    badge: null,
    metaTitle: "Solstice Crystal Belt | Maison ISIVIS",
    metaDescription: "Hand-embellished crystal belt from Maison ISIVIS.",
    keywords: ["crystal belt", "waist belt", "luxury accessory"],
    displayOrder: 1,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "prod-22",
    name: "Cashmere Evening Wrap",
    slug: "cashmere-evening-wrap",
    sku: "ISV-AC-002",
    shortDescription: "Oversized pure cashmere wrap in signature colours.",
    description: "The ultimate luxury layering piece. Woven from 100% pure Mongolian cashmere, this oversized wrap is impossibly soft and warm. The generous size allows multiple styling options — wear as a scarf, wrap, or even a blanket for travel. Finished with hand-rolled edges for a refined look.",
    price: 198,
    salePrice: null,
    compareAtPrice: null,
    inStock: true,
    stockQuantity: 28,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("cashmere-evening-wrap"),
    videoUrl: null,
    categoryId: "cat-11",
    categoryIds: ["cat-11"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Ivory", "Black", "Beige"], ["One Size"], 198),
    fabric: "100% Mongolian Cashmere",
    careInstructions: "Hand wash cold with cashmere shampoo. Lay flat to dry.",
    measurements: { "Width": "70cm", "Length": "200cm" },
    featured: false,
    newArrival: false,
    bestseller: true,
    badge: "Best Seller",
    metaTitle: "Cashmere Evening Wrap | Maison ISIVIS",
    metaDescription: "Pure cashmere evening wrap from Maison ISIVIS.",
    keywords: ["cashmere wrap", "scarf", "luxury accessory"],
    displayOrder: 2,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "prod-23",
    name: "Pearl Drop Hair Comb",
    slug: "pearl-drop-hair-comb",
    sku: "ISV-AC-003",
    shortDescription: "Freshwater pearl and crystal hair comb for bridal or evening wear.",
    description: "The Pearl Drop hair comb is the finishing touch for any special occasion. Featuring cascading freshwater pearls and Swarovski crystals set in gold-plated metal, it adds ethereal elegance to any hairstyle. Handcrafted by our accessories artisans, each piece is unique.",
    price: 89,
    salePrice: null,
    compareAtPrice: null,
    inStock: true,
    stockQuantity: 15,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("pearl-drop-hair-comb"),
    videoUrl: null,
    categoryId: "cat-11",
    categoryIds: ["cat-11"],
    categories: [],
    hasVariants: true,
    variants: makeVariants(["Diamond"], ["One Size"], 89),
    fabric: "Gold-plated metal, Freshwater pearls, Swarovski crystals",
    careInstructions: "Store in jewellery box. Clean with soft cloth.",
    measurements: { "Width": "8cm", "Height": "6cm" },
    featured: false,
    newArrival: true,
    bestseller: false,
    badge: "New",
    metaTitle: "Pearl Drop Hair Comb | Maison ISIVIS",
    metaDescription: "Pearl and crystal hair comb from Maison ISIVIS.",
    keywords: ["hair comb", "bridal accessory", "pearl"],
    displayOrder: 3,
    published: true,
    createdAt: "2025-02-05T00:00:00Z",
    updatedAt: "2025-02-05T00:00:00Z",
  },
  {
    id: "prod-24",
    name: "Silk Pocket Square Set",
    slug: "silk-pocket-square-set",
    sku: "ISV-AC-004",
    shortDescription: "Set of three hand-printed silk pocket squares.",
    description: "A set of three silk pocket squares, each featuring an exclusive ISIVIS print. Hand-printed on premium mulberry silk with hand-rolled edges. Presented in our signature gift box, they make the perfect gift. Each square can be styled as a neckerchief, bag accessory, or classic pocket square.",
    price: 98,
    salePrice: 78,
    compareAtPrice: 98,
    inStock: true,
    stockQuantity: 35,
    lowStockThreshold: 5,
    allowBackorder: false,
    images: makeImages("silk-pocket-square-set"),
    videoUrl: null,
    categoryId: "cat-11",
    categoryIds: ["cat-11"],
    categories: [],
    hasVariants: false,
    variants: [],
    fabric: "100% Mulberry Silk",
    careInstructions: "Hand wash cold. Iron on low heat.",
    measurements: { "Size": "45cm x 45cm each" },
    featured: false,
    newArrival: false,
    bestseller: false,
    badge: "Sale",
    metaTitle: "Silk Pocket Square Set | Maison ISIVIS",
    metaDescription: "Hand-printed silk pocket square set from Maison ISIVIS.",
    keywords: ["pocket square", "silk scarf", "gift set"],
    displayOrder: 4,
    published: true,
    createdAt: ts,
    updatedAt: ts,
  },
];

// ─── Collection → Product mappings ────────────────────────

export const COLLECTION_PRODUCT_MAP: Record<string, string[]> = {
  "best-sellers": ["prod-1", "prod-2", "prod-5", "prod-9", "prod-13", "prod-18", "prod-22"],
  "old-money": ["prod-1", "prod-9", "prod-12", "prod-14", "prod-17", "prod-18", "prod-22"],
  "fierce": ["prod-2", "prod-5", "prod-8", "prod-13", "prod-20", "prod-21"],
  "contemporary": ["prod-3", "prod-6", "prod-10", "prod-15", "prod-16", "prod-19", "prod-23"],
};

// ─── Reviews ──────────────────────────────────────────────

export const MOCK_REVIEWS: Review[] = [
  { id: "rev-1", userId: "u1", productId: "prod-1", rating: 5, title: "Absolutely stunning", comment: "The silk quality is incredible. I wore this to a wedding and received so many compliments. The fit is perfect and the draping is beautiful. Worth every penny.", verified: true, featured: true, approved: true, createdAt: "2025-01-10T00:00:00Z", updatedAt: "2025-01-10T00:00:00Z", user: { fullName: "Sophie M." } },
  { id: "rev-2", userId: "u2", productId: "prod-1", rating: 4, title: "Beautiful dress", comment: "Love the quality and cut. Runs slightly small so I'd recommend sizing up. The silk is buttery soft.", verified: true, featured: false, approved: true, createdAt: "2025-01-15T00:00:00Z", updatedAt: "2025-01-15T00:00:00Z", user: { fullName: "Emma R." } },
  { id: "rev-3", userId: "u3", productId: "prod-2", rating: 5, title: "A work of art", comment: "The crystal detailing is breathtaking. I felt like royalty at my gala. The corset back gives a perfect fit. This is couture quality.", verified: true, featured: true, approved: true, createdAt: "2024-12-20T00:00:00Z", updatedAt: "2024-12-20T00:00:00Z", user: { fullName: "Charlotte W." } },
  { id: "rev-4", userId: "u4", productId: "prod-2", rating: 5, title: "Investment piece", comment: "Expensive but you get what you pay for. The craftsmanship is outstanding. Every crystal is perfectly placed.", verified: true, featured: false, approved: true, createdAt: "2025-01-05T00:00:00Z", updatedAt: "2025-01-05T00:00:00Z", user: { fullName: "Amara J." } },
  { id: "rev-5", userId: "u5", productId: "prod-5", rating: 5, title: "Best corset I own", comment: "The structure is amazing and the crystals are so sparkly. I paired it with high-waisted trousers and got non-stop compliments.", verified: true, featured: true, approved: true, createdAt: "2025-01-20T00:00:00Z", updatedAt: "2025-01-20T00:00:00Z", user: { fullName: "Priya K." } },
  { id: "rev-6", userId: "u6", productId: "prod-5", rating: 4, title: "Gorgeous but snug", comment: "The corset is stunning but runs tight. I should have gone up a size. The crystal work is impeccable though.", verified: true, featured: false, approved: true, createdAt: "2025-02-01T00:00:00Z", updatedAt: "2025-02-01T00:00:00Z", user: { fullName: "Olivia T." } },
  { id: "rev-7", userId: "u7", productId: "prod-9", rating: 5, title: "Perfection", comment: "These trousers are everything. The wool quality is outstanding and the wide leg is incredibly flattering. I bought them in two colours.", verified: true, featured: false, approved: true, createdAt: "2024-11-15T00:00:00Z", updatedAt: "2024-11-15T00:00:00Z", user: { fullName: "Isabella F." } },
  { id: "rev-8", userId: "u8", productId: "prod-13", rating: 5, title: "Show-stopping set", comment: "Wore the Celestial co-ord to a party and felt like a goddess. The silk quality is amazing and the crystal straps are such a beautiful detail.", verified: true, featured: true, approved: true, createdAt: "2025-01-28T00:00:00Z", updatedAt: "2025-01-28T00:00:00Z", user: { fullName: "Zara H." } },
  { id: "rev-9", userId: "u9", productId: "prod-17", rating: 5, title: "Regal and luxurious", comment: "The vegan fur is incredibly realistic and the silk lining is such a lovely touch. I feel like royalty every time I wear it.", verified: true, featured: false, approved: true, createdAt: "2024-12-10T00:00:00Z", updatedAt: "2024-12-10T00:00:00Z", user: { fullName: "Victoria L." } },
  { id: "rev-10", userId: "u10", productId: "prod-18", rating: 5, title: "Wardrobe staple", comment: "This blazer is the best investment I've made. The Italian wool is beautiful and the gold buttons elevate it. Works for office and evening.", verified: true, featured: false, approved: true, createdAt: "2025-02-05T00:00:00Z", updatedAt: "2025-02-05T00:00:00Z", user: { fullName: "Grace N." } },
  { id: "rev-11", userId: "u11", productId: "prod-3", rating: 4, title: "Romantic and beautiful", comment: "The lace is exquisite and the corset structure is very flattering. Only giving 4 stars because the boning can be felt after long wear.", verified: true, featured: false, approved: true, createdAt: "2025-02-08T00:00:00Z", updatedAt: "2025-02-08T00:00:00Z", user: { fullName: "Hannah B." } },
  { id: "rev-12", userId: "u12", productId: "prod-22", rating: 5, title: "Incredibly soft", comment: "The cashmere quality is outstanding. So soft and warm, yet lightweight enough for evening wear. The size is generous which I love.", verified: true, featured: false, approved: true, createdAt: "2025-01-30T00:00:00Z", updatedAt: "2025-01-30T00:00:00Z", user: { fullName: "Mia C." } },
];

// ─── Mock Orders ──────────────────────────────────────────

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-1",
    orderNumber: "ISV-2025-0001",
    userId: "u1",
    shippingAddress: { fullName: "Sophie Mitchell", phone: "+44 7700 900123", addressLine1: "42 Kensington Gardens", city: "London", state: "Greater London", pinCode: "W8 4PX", country: "United Kingdom" },
    subtotal: 546,
    shippingCost: 0,
    tax: 109.2,
    discount: 0,
    total: 655.2,
    promoCode: null,
    status: "delivered",
    paymentStatus: "paid",
    paymentMethod: "stripe",
    razorpayOrderId: null,
    razorpayPaymentId: null,
    stripePaymentIntentId: "pi_mock_001",
    trackingNumber: "RM1234567890GB",
    estimatedDeliveryDate: "2025-01-18T00:00:00Z",
    notes: null,
    items: [
      { id: "oi-1", orderId: "ord-1", productId: "prod-1", productName: "Selene Silk Midi Dress", productSlug: "selene-silk-midi-dress", variantId: "ivory-s", variantName: "Ivory / S", quantity: 1, price: 298, imageUrl: "/images/products/selene-silk-midi-dress-1.webp" },
      { id: "oi-2", orderId: "ord-1", productId: "prod-5", productName: "Aria Crystal Corset", productSlug: "aria-crystal-corset", variantId: "diamond-s", variantName: "Diamond / S", quantity: 1, price: 248, imageUrl: "/images/products/aria-crystal-corset-1.webp" },
    ],
    createdAt: "2025-01-12T14:30:00Z",
    updatedAt: "2025-01-18T10:00:00Z",
  },
  {
    id: "ord-2",
    orderNumber: "ISV-2025-0002",
    userId: "u1",
    shippingAddress: { fullName: "Sophie Mitchell", phone: "+44 7700 900123", addressLine1: "42 Kensington Gardens", city: "London", state: "Greater London", pinCode: "W8 4PX", country: "United Kingdom" },
    subtotal: 398,
    shippingCost: 0,
    tax: 79.6,
    discount: 39.8,
    total: 437.8,
    promoCode: "WELCOME10",
    status: "shipped",
    paymentStatus: "paid",
    paymentMethod: "stripe",
    razorpayOrderId: null,
    razorpayPaymentId: null,
    stripePaymentIntentId: "pi_mock_002",
    trackingNumber: "RM9876543210GB",
    estimatedDeliveryDate: "2025-02-12T00:00:00Z",
    notes: "Please leave with concierge if not home.",
    items: [
      { id: "oi-3", orderId: "ord-2", productId: "prod-3", productName: "Celeste Lace Corset Dress", productSlug: "celeste-lace-corset-dress", variantId: "ivory-m", variantName: "Ivory / M", quantity: 1, price: 398, imageUrl: "/images/products/celeste-lace-corset-dress-1.webp" },
    ],
    createdAt: "2025-02-05T09:15:00Z",
    updatedAt: "2025-02-08T16:00:00Z",
  },
  {
    id: "ord-3",
    orderNumber: "ISV-2025-0003",
    userId: "u1",
    shippingAddress: { fullName: "Sophie Mitchell", phone: "+44 7700 900123", addressLine1: "42 Kensington Gardens", city: "London", state: "Greater London", pinCode: "W8 4PX", country: "United Kingdom" },
    subtotal: 198,
    shippingCost: 4.99,
    tax: 39.6,
    discount: 0,
    total: 242.59,
    promoCode: null,
    status: "processing",
    paymentStatus: "paid",
    paymentMethod: "razorpay",
    razorpayOrderId: "order_mock_003",
    razorpayPaymentId: "pay_mock_003",
    stripePaymentIntentId: null,
    trackingNumber: null,
    estimatedDeliveryDate: null,
    notes: null,
    items: [
      { id: "oi-4", orderId: "ord-3", productId: "prod-9", productName: "Serena Tailored Trousers", productSlug: "serena-tailored-trousers", variantId: "black-m", variantName: "Black / M", quantity: 1, price: 198, imageUrl: "/images/products/serena-tailored-trousers-1.webp" },
    ],
    createdAt: "2025-02-10T11:00:00Z",
    updatedAt: "2025-02-10T11:00:00Z",
  },
];

// ─── Mock Addresses ───────────────────────────────────────

export const MOCK_ADDRESSES: Address[] = [
  {
    id: "addr-1",
    userId: "u1",
    fullName: "Sophie Mitchell",
    phone: "+44 7700 900123",
    addressLine1: "42 Kensington Gardens",
    addressLine2: "Flat 3",
    city: "London",
    state: "Greater London",
    pinCode: "W8 4PX",
    country: "United Kingdom",
    isDefault: true,
    createdAt: ts,
    updatedAt: ts,
  },
  {
    id: "addr-2",
    userId: "u1",
    fullName: "Sophie Mitchell",
    phone: "+44 7700 900123",
    addressLine1: "15 Mayfair Street",
    addressLine2: null,
    city: "London",
    state: "Greater London",
    pinCode: "W1K 6LB",
    country: "United Kingdom",
    isDefault: false,
    createdAt: ts,
    updatedAt: ts,
  },
];

// ─── Query Helper Functions ───────────────────────────────

export function getProductBySlug(slug: string): Product | undefined {
  const product = MOCK_PRODUCTS.find((p) => p.slug === slug && p.published);
  if (!product) return undefined;
  // Join categories (multi-category aware)
  const cats = MOCK_CATEGORIES.filter((c) => (product.categoryIds ?? []).includes(c.id) || c.id === product.categoryId);
  return { ...product, categories: cats, category: cats[0] };
}

export function getProductById(id: string): Product | undefined {
  const product = MOCK_PRODUCTS.find((p) => p.id === id && p.published);
  if (!product) return undefined;
  // Join categories (multi-category aware)
  const cats = MOCK_CATEGORIES.filter((c) => (product.categoryIds ?? []).includes(c.id) || c.id === product.categoryId);
  return { ...product, categories: cats, category: cats[0] };
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return MOCK_CATEGORIES.find((c) => c.slug === slug);
}

export function getCollectionBySlug(slug: string): Collection | undefined {
  return MOCK_COLLECTIONS.find((c) => c.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  const category = getCategoryBySlug(categorySlug);
  if (!category) return [];
  return MOCK_PRODUCTS.filter((p) => ((p.categoryIds ?? []).includes(category.id) || p.categoryId === category.id) && p.published);
}

export function getProductsByCollection(collectionSlug: string): Product[] {
  const productIds = COLLECTION_PRODUCT_MAP[collectionSlug];
  if (!productIds) return [];
  return MOCK_PRODUCTS.filter((p) => productIds.includes(p.id) && p.published);
}

export function getRelatedProducts(productId: string, limit = 4): Product[] {
  const product = getProductById(productId);
  if (!product) return [];
  const productCatIds = product.categoryIds?.length ? product.categoryIds : (product.categoryId ? [product.categoryId] : []);
  if (productCatIds.length === 0) return [];
  return MOCK_PRODUCTS.filter(
    (p) => p.id !== productId && p.published && (p.categoryIds ?? []).some((cid) => productCatIds.includes(cid))
  ).slice(0, limit);
}

export function getReviewsByProduct(productId: string): Review[] {
  return MOCK_REVIEWS.filter((r) => r.productId === productId && r.approved);
}

export function getFilteredProducts(filters: ProductFilters = {}): PaginatedProducts {
  let products = MOCK_PRODUCTS.filter((p) => p.published);

  // Category filter
  if (filters.categorySlug) {
    const category = getCategoryBySlug(filters.categorySlug);
    if (category) {
      products = products.filter((p) => (p.categoryIds ?? []).includes(category.id) || p.categoryId === category.id);
    }
  }

  // Collection filter
  if (filters.collectionSlug) {
    const productIds = COLLECTION_PRODUCT_MAP[filters.collectionSlug];
    if (productIds) {
      products = products.filter((p) => productIds.includes(p.id));
    }
  }

  // Price range
  if (filters.minPrice != null) {
    products = products.filter((p) => (p.salePrice ?? p.price) >= filters.minPrice!);
  }
  if (filters.maxPrice != null) {
    products = products.filter((p) => (p.salePrice ?? p.price) <= filters.maxPrice!);
  }

  // Size filter
  if (filters.sizes && filters.sizes.length > 0) {
    products = products.filter((p) =>
      p.variants.some(
        (v) => v.size && filters.sizes!.includes(v.size) && v.stock > 0
      )
    );
  }

  // Color filter
  if (filters.colors && filters.colors.length > 0) {
    products = products.filter((p) =>
      p.variants.some(
        (v) => v.color && filters.colors!.includes(v.color) && v.stock > 0
      )
    );
  }

  // In stock only
  if (filters.inStockOnly) {
    products = products.filter((p) => p.inStock && p.stockQuantity > 0);
  }

  // On sale
  if (filters.onSale) {
    products = products.filter((p) => p.salePrice != null);
  }

  // New arrivals
  if (filters.newArrivals) {
    products = products.filter((p) => p.newArrival);
  }

  // Search
  if (filters.search) {
    const q = filters.search.toLowerCase();
    products = products.filter(
      (p) =>
        p.name.toLowerCase().includes(q) ||
        (p.shortDescription ?? "").toLowerCase().includes(q) ||
        (p.description ?? "").toLowerCase().includes(q) ||
        p.sku.toLowerCase().includes(q)
    );
  }

  // Sorting
  const sortBy = filters.sortBy ?? "featured";
  switch (sortBy) {
    case "featured":
      products.sort((a, b) => (b.featured ? 1 : 0) - (a.featured ? 1 : 0) || a.displayOrder - b.displayOrder);
      break;
    case "newest":
      products.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
      break;
    case "price-asc":
      products.sort((a, b) => (a.salePrice ?? a.price) - (b.salePrice ?? b.price));
      break;
    case "price-desc":
      products.sort((a, b) => (b.salePrice ?? b.price) - (a.salePrice ?? a.price));
      break;
    case "bestseller":
      products.sort((a, b) => (b.bestseller ? 1 : 0) - (a.bestseller ? 1 : 0));
      break;
    case "name-asc":
      products.sort((a, b) => a.name.localeCompare(b.name));
      break;
  }

  // Pagination
  const page = filters.page ?? 1;
  const limit = filters.limit ?? 12;
  const total = products.length;
  const totalPages = Math.ceil(total / limit);
  const start = (page - 1) * limit;
  const paginated = products.slice(start, start + limit);

  return { products: paginated, total, page, limit, totalPages };
}
