// This file will be auto-generated by Supabase CLI via:
//   npx supabase gen types typescript --linked > src/types/database.ts
// For now, provide a minimal placeholder so imports don't break.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          phone: string | null;
          avatar_url: string | null;
          role: "customer" | "admin";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          phone?: string | null;
          avatar_url?: string | null;
          role?: "customer" | "admin";
        };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Insert"]>;
      };
      categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          image_url: string | null;
          parent_id: string | null;
          show_in_menu: boolean;
          display_order: number;
          meta_title: string | null;
          meta_description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          name: string;
          slug: string;
          description?: string | null;
          image_url?: string | null;
          parent_id?: string | null;
          show_in_menu?: boolean;
          display_order?: number;
          meta_title?: string | null;
          meta_description?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["categories"]["Insert"]>;
      };
      collections: {
        Row: {
          id: string;
          title: string;
          slug: string;
          description: string | null;
          hero_image_url: string | null;
          hero_video_url: string | null;
          collection_type:
            | "featured"
            | "style"
            | "seasonal"
            | "curated"
            | null;
          featured: boolean;
          display_order: number;
          meta_title: string | null;
          meta_description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          title: string;
          slug: string;
          description?: string | null;
          hero_image_url?: string | null;
          hero_video_url?: string | null;
          collection_type?:
            | "featured"
            | "style"
            | "seasonal"
            | "curated"
            | null;
          featured?: boolean;
          display_order?: number;
          meta_title?: string | null;
          meta_description?: string | null;
        };
        Update: Partial<
          Database["public"]["Tables"]["collections"]["Insert"]
        >;
      };
      products: {
        Row: {
          id: string;
          name: string;
          slug: string;
          sku: string;
          short_description: string | null;
          description: string | null;
          price: number;
          sale_price: number | null;
          compare_at_price: number | null;
          in_stock: boolean;
          stock_quantity: number;
          low_stock_threshold: number;
          allow_backorder: boolean;
          images: Json;
          video_url: string | null;
          category_id: string | null;
          has_variants: boolean;
          variants: Json;
          fabric: string | null;
          care_instructions: string | null;
          measurements: Json | null;
          featured: boolean;
          new_arrival: boolean;
          bestseller: boolean;
          badge: string | null;
          meta_title: string | null;
          meta_description: string | null;
          keywords: string[] | null;
          display_order: number;
          published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          name: string;
          slug: string;
          sku: string;
          short_description?: string | null;
          description?: string | null;
          price: number;
          sale_price?: number | null;
          compare_at_price?: number | null;
          in_stock?: boolean;
          stock_quantity?: number;
          low_stock_threshold?: number;
          allow_backorder?: boolean;
          images?: Json;
          video_url?: string | null;
          category_id?: string | null;
          has_variants?: boolean;
          variants?: Json;
          fabric?: string | null;
          care_instructions?: string | null;
          measurements?: Json | null;
          featured?: boolean;
          new_arrival?: boolean;
          bestseller?: boolean;
          badge?: string | null;
          meta_title?: string | null;
          meta_description?: string | null;
          keywords?: string[] | null;
          display_order?: number;
          published?: boolean;
        };
        Update: {
          name?: string;
          slug?: string;
          sku?: string;
          short_description?: string | null;
          description?: string | null;
          price?: number;
          sale_price?: number | null;
          compare_at_price?: number | null;
          in_stock?: boolean;
          stock_quantity?: number;
          low_stock_threshold?: number;
          allow_backorder?: boolean;
          images?: Json;
          video_url?: string | null;
          category_id?: string | null;
          has_variants?: boolean;
          variants?: Json;
          fabric?: string | null;
          care_instructions?: string | null;
          measurements?: Json | null;
          featured?: boolean;
          new_arrival?: boolean;
          bestseller?: boolean;
          badge?: string | null;
          meta_title?: string | null;
          meta_description?: string | null;
          keywords?: string[] | null;
          display_order?: number;
          published?: boolean;
        };
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          user_id: string | null;
          shipping_address: Json;
          subtotal: number;
          shipping_cost: number;
          tax: number;
          discount: number;
          total: number;
          promo_code: string | null;
          status:
            | "pending"
            | "confirmed"
            | "processing"
            | "shipped"
            | "delivered"
            | "cancelled"
            | "refunded";
          payment_status: "pending" | "paid" | "failed" | "refunded";
          payment_method: "razorpay" | "stripe" | "cod";
          razorpay_order_id: string | null;
          razorpay_payment_id: string | null;
          razorpay_signature: string | null;
          stripe_payment_intent_id: string | null;
          tracking_number: string | null;
          estimated_delivery_date: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id?: string | null;
          shipping_address: Json;
          subtotal: number;
          shipping_cost?: number;
          tax?: number;
          discount?: number;
          total: number;
          promo_code?: string | null;
          status?:
            | "pending"
            | "confirmed"
            | "processing"
            | "shipped"
            | "delivered"
            | "cancelled"
            | "refunded";
          payment_status?: "pending" | "paid" | "failed" | "refunded";
          payment_method: "razorpay" | "stripe" | "cod";
          razorpay_order_id?: string | null;
          razorpay_payment_id?: string | null;
          razorpay_signature?: string | null;
          stripe_payment_intent_id?: string | null;
          tracking_number?: string | null;
          estimated_delivery_date?: string | null;
          notes?: string | null;
        };
        Update: Partial<Database["public"]["Tables"]["orders"]["Insert"]>;
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string | null;
          product_name: string;
          product_slug: string;
          variant_id: string | null;
          variant_name: string | null;
          quantity: number;
          price: number;
          image_url: string | null;
          created_at: string;
        };
        Insert: {
          order_id: string;
          product_id?: string | null;
          product_name: string;
          product_slug: string;
          variant_id?: string | null;
          variant_name?: string | null;
          quantity: number;
          price: number;
          image_url?: string | null;
        };
        Update: Partial<
          Database["public"]["Tables"]["order_items"]["Insert"]
        >;
      };
      wishlist_items: {
        Row: {
          id: string;
          user_id: string;
          product_id: string;
          created_at: string;
        };
        Insert: {
          user_id: string;
          product_id: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["wishlist_items"]["Insert"]
        >;
      };
      reviews: {
        Row: {
          id: string;
          user_id: string;
          product_id: string;
          rating: number;
          title: string | null;
          comment: string | null;
          verified: boolean;
          featured: boolean;
          approved: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          product_id: string;
          rating: number;
          title?: string | null;
          comment?: string | null;
          verified?: boolean;
          featured?: boolean;
          approved?: boolean;
        };
        Update: Partial<Database["public"]["Tables"]["reviews"]["Insert"]>;
      };
      addresses: {
        Row: {
          id: string;
          user_id: string;
          full_name: string;
          phone: string;
          address_line1: string;
          address_line2: string | null;
          city: string;
          state: string;
          pin_code: string;
          country: string;
          is_default: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          full_name: string;
          phone: string;
          address_line1: string;
          address_line2?: string | null;
          city: string;
          state: string;
          pin_code: string;
          country?: string;
          is_default?: boolean;
        };
        Update: Partial<Database["public"]["Tables"]["addresses"]["Insert"]>;
      };
      promo_codes: {
        Row: {
          id: string;
          code: string;
          description: string | null;
          type: "percentage" | "fixed";
          value: number;
          min_order_value: number | null;
          max_discount: number | null;
          usage_limit: number | null;
          usage_count: number;
          user_limit: number | null;
          start_date: string;
          expires_at: string;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          code: string;
          description?: string | null;
          type: "percentage" | "fixed";
          value: number;
          min_order_value?: number | null;
          max_discount?: number | null;
          usage_limit?: number | null;
          usage_count?: number;
          user_limit?: number | null;
          start_date: string;
          expires_at: string;
          active?: boolean;
        };
        Update: Partial<
          Database["public"]["Tables"]["promo_codes"]["Insert"]
        >;
      };
      newsletter_subscribers: {
        Row: {
          id: string;
          email: string;
          subscribed: boolean;
          source: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          email: string;
          subscribed?: boolean;
          source?: string | null;
        };
        Update: Partial<
          Database["public"]["Tables"]["newsletter_subscribers"]["Insert"]
        >;
      };
      product_collections: {
        Row: {
          product_id: string;
          collection_id: string;
          created_at: string;
        };
        Insert: {
          product_id: string;
          collection_id: string;
        };
        Update: Partial<
          Database["public"]["Tables"]["product_collections"]["Insert"]
        >;
      };
      site_settings: {
        Row: {
          id: string;
          key: string;
          value: Json;
          updated_at: string;
        };
        Insert: {
          key: string;
          value: Json;
        };
        Update: Partial<
          Database["public"]["Tables"]["site_settings"]["Insert"]
        >;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      order_status:
        | "pending"
        | "confirmed"
        | "processing"
        | "shipped"
        | "delivered"
        | "cancelled"
        | "refunded";
      payment_status: "pending" | "paid" | "failed" | "refunded";
      payment_method: "razorpay" | "stripe" | "cod";
      promo_type: "percentage" | "fixed";
    };
    CompositeTypes: Record<string, never>;
  };
}
